services:
  - type: web
    name: fulfulde-translator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
